name: Pandora CI

on:
  push:
  schedule:
   - cron:  0 2 * * *


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Pandora with dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e --no-build-isolation .[dev]

    - name: Test with pytest
      run: |
        export NUMBA_DISABLE_JIT="1"
        pytest -m "not notebook_tests" --junitxml=pytest-report.xml --cov-config=.coveragerc --cov-report xml --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
